In [77]:
import numpy as np
my_array = np.array([1, 2, 3, 4])
print("1d array")
print(my_array)
print("2d array")
array_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)
arr_3d = np.array([
  [[ 1,  2,  3,  4],
   [ 5,  6,  7,  8],
   [ 9, 10, 11, 12]],
  [[13, 14, 15, 16],
   [17, 18, 19, 20],
   [21, 22, 23, 24]]
])
print(arr_3d)
print(arr_3d.ndim)

1d array
[1 2 3 4]
2d array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3


In [78]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [79]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [80]:
random_array = np.random.random((2,2))
print(random_array)

[[0.98250965 0.40794742]
 [0.23229005 0.83963701]]


In [81]:
arr_identity=np.eye(3)
print(arr_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [82]:
range_arr = np.arange(0,10,2) #start, stop, index
print(range_arr)

[0 2 4 6 8]


In [83]:
test_arr = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(test_arr.shape)
print(test_arr.size)
print(test_arr.dtype)
print(test_arr.ndim)

(3, 3)
9
int64
2


In [84]:
#smart_agri
temp_data = np.array([[22,25,20], [24,26,23]])
print(temp_data.shape)
print(temp_data.size)
print(temp_data.dtype)
print(temp_data.ndim)
GH3 = np.array([21, 23, 22])
updated_temp_data=np.array([[22,25,20], [24,26,23],[21, 23, 22]])
sensor_error_flags = np.zeros((2,3))
greenhouse_identity = np.eye(3)
print("updated_temp_data")
print(updated_temp_data)
print("sensor_error_flags")
print(sensor_error_flags)
print("greenhouse_identity")
print(greenhouse_identity)

(2, 3)
6
int64
2
updated_temp_data
[[22 25 20]
 [24 26 23]
 [21 23 22]]
sensor_error_flags
[[0. 0. 0.]
 [0. 0. 0.]]
greenhouse_identity
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [85]:
temp_data = np.array([[22,25,20], [24,26,23]])
print(temp_data[1,2])

23


In [86]:
# Filtering
# Create a 1D array of random integers between 1 and 50.
# Extract all elements that are divisible by 5.
arr = np.random.randint(1, 51, size=10) # Create an array of 10 random integers
print(f"Generated array: {arr}")
print(f"Elements divisible by 5: {arr[arr % 5 == 0]}")

[[25 20]
 [26 23]]


In [87]:
mat_1 = np.array([[22,25,20],[24,26,23]])
mat_2 = np.array([[2,5,2],[4,6,3],])

print(mat_1+mat_2)
print(mat_1-mat_2)
print(mat_1*mat_2)
print(mat_1/mat_2)
mat_1 = np.array([[22,25,20],[24,26,23]])
mat_2 = np.array([[2,5,2],[4,6,3],[2,6,3]])
result = np.dot(mat_1,mat_2)
print(result)

[[24 30 22]
 [28 32 26]]
[[20 20 18]
 [20 20 20]]
[[ 44 125  40]
 [ 96 156  69]]
[[11.          5.         10.        ]
 [ 6.          4.33333333  7.66666667]]
[[184 380 179]
 [198 414 195]]


In [88]:
a=np.array([1,2,3])
b=2
print(a+b)
print(a*b)
new_array=np.sin(a)
print(new_array)
print(np.round(new_array))

[3 4 5]
[2 4 6]
[0.84147098 0.90929743 0.14112001]
[1. 1. 0.]


In [89]:
farm_a = np.array([
    [10, 12, 11],
    [9, 11, 10],
    [12, 13, 14],
    [8, 7, 9]
])


farm_b = np.array([
    [20, 19, 21],
    [18, 20, 19],
    [22, 23, 21],
    [17, 18, 16]
])


farm_c = np.array([
    [15, 16, 14],
    [14, 13, 15],
    [16, 17, 18],
    [12, 11, 13]
])

In [90]:
production_all = np.stack([farm_a, farm_b, farm_c])
print("\nStacked production data for all farms:")
print(production_all)
print("\nShape of the stacked array:")
print(production_all.shape)
print("\nSize of the stacked array (total elements):")
print(production_all.size)
print("\nData type of the stacked array:")
print(production_all.dtype)
print("\nNumber of dimensions of the stacked array:")
print(production_all.ndim)


Stacked production data for all farms:
[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]

Shape of the stacked array:
(3, 4, 3)

Size of the stacked array (total elements):
36

Data type of the stacked array:
int64

Number of dimensions of the stacked array:
3


In [91]:
# 1. Per-farm totals (arithmetic & aggregation)
print("1. Per-Farm Aggregations ")
total_per_farm = np.sum(production_all, axis=(1, 2))
mean_per_farm = np.mean(production_all, axis=(1, 2))
std_per_farm = np.std(production_all, axis=(1, 2))
var_per_farm = np.var(production_all, axis=(1, 2))

print(f"Total production per farm: {total_per_farm}")
print(f"Mean production per farm: {mean_per_farm}")
print(f"Standard deviation per farm: {std_per_farm}")
print(f"Variance per farm: {var_per_farm}\n")


# 2. Per-hour matrix multiplication
print("--- 2. Weighted Energy Calculation (Matrix Multiplication) ---")
hour_weights = np.array([0.5, 1.0, 0.75])
# Using @ operator for matrix multiplication (dot product)
weighted_per_panel = np.dot(production_all ,hour_weights)
print(f"Weighted energy per panel (shape: {weighted_per_panel.shape}):")
print(weighted_per_panel, "\n")


# 3. Broadcasting adjustments
print("--- 3. Broadcasting Calibration Offset ---")
# The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B.
# production_all[1] selects all data for Farm B.
production_all[1] = production_all[1] + 0.5
print("Farm B data after adding 0.5 kWh offset:")
print(production_all[1], "\n")


# 4. Element-wise arithmetic (Z-score normalization)
print("--- 4. Z-Score Normalization ---")
# To broadcast correctly, we need to reshape the (3,) stats arrays to (3, 1, 1)
mean_reshaped = mean_per_farm.reshape(3, 1, 1)
std_reshaped = std_per_farm.reshape(3, 1, 1)
normalized_data = (production_all - mean_reshaped) / std_reshaped
print(f"Normalized data (Z-scores) (shape: {normalized_data.shape}):")
# Showing first farm's normalized data for brevity
print("Farm A (normalized):")
print(normalized_data[0], "\n")


# 5. Applying Universal Functions (ufuncs)
print("--- 5. Universal Function Demonstrations ---")
# Exponential and Logarithmic
print("Exponential (first row of Farm A's normalized data):", np.exp(normalized_data[0, 0, :]))
# Trigonometric
print("Sine (first row of Farm A's normalized data):", np.sin(normalized_data[0, 0, :]))
# Rounding
print("Ceiling of Farm B's adjusted data:", np.ceil(production_all[1]))
# Comparison and Logical
high_output_mask = production_all > 20
print(f"\nNumber of high output instances (>20 kWh): {np.sum(high_output_mask)}")
# Create another mask, e.g., for Farm B
farm_b_mask = np.zeros_like(production_all, dtype=bool)
farm_b_mask[1, :, :] = True
# Combine masks
high_output_in_farm_b = np.logical_and(high_output_mask, farm_b_mask)
print(f"Number of high output instances in Farm B: {np.sum(high_output_in_farm_b)}\n")


# 6. Broadcast-based summary table
print("--- 6. Broadcast-Based Summary Table ---")
panel_totals_per_farm = np.sum(production_all, axis=2)
print(f"Total production per panel for each farm (shape: {panel_totals_per_farm.shape}):")
print(panel_totals_per_farm)
# A panel needs maintenance if its total production is less than 40
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print(f"\nNeeds maintenance (any panel total < 40): {needs_maintenance}\n")


# 7. Final KPIs (Key Performance Indicators)
print("--- 7. Final KPIs ---")
overall_total = np.sum(production_all)
print(f"Overall total production from all farms: {overall_total:.2f} kWh")

# Find the peak production value and its location
peak_value = np.max(production_all)
peak_flat_index = np.argmax(production_all)
peak_farm, peak_panel, peak_hour = np.unravel_index(peak_flat_index, production_all.shape)
print(f"Peak production of {peak_value:.2f} kWh was at Farm {peak_farm}, Panel {peak_panel}, Hour {peak_hour}")

# Average production per panel (averaging the panel totals)
average_per_panel = np.mean(panel_totals_per_farm)
print(f"Average production per panel across all farms: {average_per_panel:.2f} kWh")



1. Per-Farm Aggregations 
Total production per farm: [126 234 174]
Mean production per farm: [10.5 19.5 14.5]
Standard deviation per farm: [1.97905701 1.97905701 1.97905701]
Variance per farm: [3.91666667 3.91666667 3.91666667]

--- 2. Weighted Energy Calculation (Matrix Multiplication) ---
Weighted energy per panel (shape: (3, 4)):
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]] 

--- 3. Broadcasting Calibration Offset ---
Farm B data after adding 0.5 kWh offset:
[[20 19 21]
 [18 20 19]
 [22 23 21]
 [17 18 16]] 

--- 4. Z-Score Normalization ---
Normalized data (Z-scores) (shape: (3, 4, 3)):
Farm A (normalized):
[[-0.25264558  0.75793673  0.25264558]
 [-0.75793673  0.25264558 -0.25264558]
 [ 0.75793673  1.26322788  1.76851903]
 [-1.26322788 -1.76851903 -0.75793673]] 

--- 5. Universal Function Demonstrations ---
Exponential (first row of Farm A's normalized data): [0.77674313 2.13386893 1.2874269 ]
Sine (first row of Farm A's normalized data): [-0.249

In [96]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [100]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [101]:
#splitting
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [102]:
#boolean index
arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])
print(arr[arr<3])

[4 5 6]
[1 2]


In [104]:
#view vs copy
arr=np.array([1,2,3,4,5,6])
arr_copy=arr.copy()
arr_view=arr.view()
arr_view[0]=10
print(f'arr {arr}')
arr_copy[0]=10

print(f'arr_copy {arr_copy}')
print(f'arr_view {arr_view}')

arr [10  2  3  4  5  6]
arr_copy [10  2  3  4  5  6]
arr_view [10  2  3  4  5  6]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [114]:
arr1=np.arange(10,51)
arr2=np.random.random((3,3))
arr1=arr1+5
print(arr1)
arr3=np.random.random((3,3))
print(arr2*arr3)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[0.11715806 0.69709329 0.19430767]
 [0.3322925  0.45218987 0.07157733]
 [0.03250046 0.16955465 0.40073708]]


In [118]:
arr4=np.arange(1,26)
arr4=arr4.reshape(5,5)
print(arr4[0,-1])
print(arr4[:3,:2])

5
[[ 1  2]
 [ 6  7]
 [11 12]]


In [119]:

random_integers = np.random.randint(10, 101, 10)
print(f"Generated random array: {random_integers}")

max_val = np.max(random_integers)
min_val = np.min(random_integers)
print(f"Maximum value: {max_val}")
print(f"Minimum value: {min_val}")

mean_val = np.mean(random_integers)
std_val = np.std(random_integers)
print(f"Mean: {mean_val:.2f}")
print(f"Standard Deviation: {std_val:.2f}")


Generated random array: [30 29 66 70 91 94 19 66 73 26]
Maximum value: 94
Minimum value: 19
Mean: 56.40
Standard Deviation: 26.51


In [120]:
arr1=np.arange(1,13)
arr1=arr1.reshape(3,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [121]:
arr2=np.ones((3,3))
arr3=np.array([1,2,3])
arr2=arr2+arr3
print(arr2)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [125]:
arr=np.random.randint(1,51,10)
print(arr[arr%5==0])

[45 35 25]


In [129]:
arr1=np.random.randint(1,10,(2,2))
arr2=np.random.randint(1,10,(2,2))
print(f'arr1 {arr1}')
print(f'arr2 {arr2}')
print(np.dot(arr1,arr2))

arr1 [[7 7]
 [1 4]]
arr2 [[4 4]
 [6 4]]
[[70 56]
 [28 20]]


In [130]:
four_by_four = np.arange(16).reshape(4, 4)
print("Original 4x4 Array:")
print(four_by_four)

rows = np.array([0, 1, 2, 3])
cols = np.array([0, 1, 2, 3])
diagonal = four_by_four[rows, cols]
print(f"\nExtracted Diagonal: {diagonal}")

# A more concise way to get the diagonal
print(f"Diagonal (concise method): {np.diag(four_by_four)}")


Original 4x4 Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted Diagonal: [ 0  5 10 15]
Diagonal (concise method): [ 0  5 10 15]
